# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4e1027c9e01d4f20cd8713411867df6546c77c832a92768d548bc7ee7118e6c8ac4ca860604e18cb5028dd535e8625fdfb535195d2c258e9a816f9cadf17c62

test:
  secret_key_base: 4c6322f122f48ad66300a8b0df3d3aac5585ec641cc594fbbab236a5add934b45a70be14d1bb57fab0e8936e8c5a3423c998be8a928c0b6e181f97d0542e1854

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
